window.posters = {
  zeid: {
    company: 'Richard Zeid Design',
    creator: 'Richard Zeid',
    description:
      '“I discovered with a simple turn of the Equality Illinois logo that the abbreviation of Illinois made itself evident. This made me think that Equality IS IL and Illinois is for equality. The two work seamlessly together, just as it should be.',
    images: ['zeid.jpg', 'zeid-2.jpg', 'zeid-3.jpg'],
    medium: '24″ x 36″, lasercut',
    price: '$45.00',
    title: '“=IL”',
    url: 'http://www.rzdesign.com',
  },
  hawthorne: {
    creator: 'Adrianne Hawthorne',
    description:
      '“You never truly know someone until you’ve walked a mile in their shoes.” – Unknown',
    images: ['hawthorne.jpg', 'hawthorne-2.jpg', 'hawthorne-3.jpg'],
    medium: '16″ x 20″, silkscreen',
    price: '$40.00',
    title: '“The Shoe Adage”',
    url: 'http://adriannehawthorne.com/#/home',
  },
  lawson: {
    company: 'Chicago Art Department',
    creator: 'Dud Lawson',
    description:
      'I only knew two things about my kindergarten art teacher: he was gay and he always drank Tab. This one’s for you, Mr. Satterfield.',
    images: ['lawson.png', 'lawson-2.jpg', 'lawson-3.jpg'],
    medium: '12ʺ x 18ʺ, ink and house paint on paper',
    price: '$40.00',
    title: '“The Pink Can”',
    url: 'http://www.chicagoartdepartment.org',
  },
  helbach: {
    creator: 'Alexander Helbach',
    description:
      'Frances Wright (1795-1852) was a feminist, writer and reformer. Her advocacy and views on freedom for all inspired me to create this poster. I’m sure, if she were alive today, Ms. Wright would be at the forefront of advocating equality for the LGBT community.',
    images: ['helbach.jpg', 'helbach-2.jpg', 'helbach-3.jpg'],
    medium: '18ʺ x 24ʺ, silkscreen',
    price: '$40.00',
    title: '“The Soul of Liberty”',
    url: 'http://alexanderhelbach.squarespace.com',
  },
  polyak: {
    creator: 'Dan Polyak',
    description:
      'Continuing use of this pedantic term is justifying the idea that there is still something different between ‘same-sex’ marriage and ‘opposite-sex’ marriage.',
    images: ['polyak.jpg', 'polyak-2.jpg', 'polyak-3.jpg'],
    medium: '15.5ʺ x 28ʺ, acrylic paint on paper',
    price: '$40.00',
    title: '“It’s Just Marriage”',
    url: 'http://danpolyak.com',
  },
  perrott: {
    company: 'Haypeep',
    creator: 'Sage Perrott',
    description:
      'Discriminatory practices harm everyone in a society. Basic rights should be enjoyed by the whole, not just the few.',
    images: ['perrott.jpg', 'perrott-2.jpg', 'perrott-3.jpg'],
    medium: '16ʺ x 20ʺ, silkscreen',
    price: '$40.00',
    title: '“Love is for everyone”',
    url: 'http://www.haypeep.bigcartel.com',
  },
  knowlden: {
    company: 'Wellmade',
    creator: 'Brandon Knowlden',
    description:
      'I just wanted to create something simple and beautiful — much like anyone else in this world.',
    images: ['knowlden.jpg', 'knowlden-2.jpg', 'knowlden-3.jpg'],
    medium: '16ʺ x 20ʺ, giclée',
    price: '$60.00',
    title: '“It’s About Time”',
    url: 'http://www.wearewellmade.com',
  },
  barthold: {
    company: 'monstersongs',
    creator: 'Jillian Barthold',
    description:
      'We fight for our rights in a menagerie of ways - you don’t have to be in the midst of a protest to bring about positive change. With enough love, action, and support, we have the power to change history and create a world where love is just that, love.',
    images: ['barthold.jpg', 'barthold-2.jpg', 'barthold-3.jpg'],
    medium: '16ʺ x 20ʺ, silkscreen',
    price: '$40.00',
    url: 'https://www.etsy.com/shop/monstersongs',
    title: '“Picket Line”',
  },
  black: {
    creator: 'Jonathan Black',
    description:
      'When two people love one another, they should be able to share their happiness with the rest of the world. This piece highlights two grooms, and the moments they share on their special day.',
    images: ['black.jpg', 'black-2.jpg', 'black-3.jpg'],
    medium: '18ʺ x 24ʺ, silkscreen',
    price: '$40.00',
    title: '“Wedding Day”',
    url: 'http://www.jonathanrblack.com',
  },
  gramm: {
    creator: 'Nikole Gramm',
    description: 'A pride flag of hugs.',
    images: ['gramm.jpg', 'gramm-2.jpg', 'gramm-3.jpg'],
    medium: '16ʺ x 20ʺ, silkscreen',
    price: '$40.00',
    title: '“Love is Love”',
    url: 'http://nikolegramm.com',
  },
  pearlman: {
    creator: 'Carly Pearlman',
    description: 'Because who can argue with love?',
    images: ['pearlman.jpg', 'pearlman-2.jpg', 'pearlman-3.jpg'],
    medium: '16ʺ x 20ʺ, silkscreen',
    price: '$40.00',
    title: '“Love is Love is Love”',
    url: 'http://www.callmecarly.com',
  },
  kraner: {
    company: 'Intrinsic Made',
    creator: 'Zachary Kraner',
    description: 'We all deserve to love equally.',
    images: ['kraner.jpg', 'kraner-2.jpg', 'kraner-3.jpg'],
    medium: '19ʺ x 25ʺ, paint pen',
    price: '$40.00',
    title: 'Love Equally”',
    url: 'http://www.intrinsicmade.com',
  },
  ford: {
    company: 'Chicago Art Department',
    creator: 'Ryan Troy Ford',
    description:
      'Beyond the contrived prejudice of human beings, love is universally impartial.',
    images: ['ford.jpg', 'ford-2.jpg', 'ford-3.jpg'],
    medium: '19ʺ x 25ʺ, silkscreen',
    price: '$40.00',
    title: '“For Small Creatures”',
    url: 'http://www.chicagoartdepartment.org',
  },
  lewis: {
    company: 'Catharsis Printworks',
    creator: 'Audrey Lewis',
    description:
      '“Erasure” is a reaction to the biphobic phrases I often deal with. There are countless harmful misconceptions about bisexuality, and this invalidation often leads to depression and other serious mental health issues in bisexuals. I hope to spread awareness about common prejudices so that we may continue to create a safer and more welcoming community for all (sometimes overlooked) queer folks.',
    images: ['lewis.jpg', 'lewis-2.jpg', 'lewis-3.jpg'],
    medium: '19ʺ x 25ʺ, silkscreen',
    price: '$40.00',
    title: '“Erasure”',
    url: 'http://catharsisprintworks.com',
  },
  halfhalf: {
    company: 'Half and Half',
    creator: 'Thomas Jennings',
    description:
      'I have always been fascinated with the CMYK process. A process color alone is just that, a lone color. Only when they come together do they create something more than what they are. Now imagine if people could accept each other and exist together, could we make this world more than what it is?',
    images: ['halfhalf.jpg', 'halfhalf-2.jpg', 'halfhalf-3.jpg'],
    medium: '24ʺ x 36ʺ, silkscreen',
    price: '$40.00',
    title: '“CMYKLGBT”',
    url: 'https://www.thehalfandhalf.com',
  },
  minnich: {
    creator: 'Bryan Minnich',
    description: '',
    images: ['minnich.jpg', 'minnich-2.jpg', 'minnich-3.jpg'],
    medium: '19ʺ x 25ʺ, silkscreen',
    price: '$40.00',
    title: '“Birds Do It”',
    url: 'http://bryanminnich.com',
  },
  burnell: {
    creator: 'Patrick Burnell',
    description:
      'I wanted to create a piece that was fun and lively, and in support of just people loving each other. It seems like people don’t do enough of that these days. Everybody, just love!',
    images: ['burnell.jpg', 'burnell-2.jpg', 'burnell-3.jpg'],
    medium: '16ʺ x 20ʺ, silkscreen',
    price: '$40.00',
    title: '“LOVE”',
    url: 'http://patrickburnell.com',
  },
  vetter: {
    creator: 'Brad Vetter',
    description:
      'As I began working on this print, the National Park Service made the announcement that they would begin to include historic LGBT sites (ie. Stonewall Inn) as National Landmarks. This sort of progress and inclusion gets me excited about living in the good ole USA. This print is a celebration of these United States, and all of the people and places that make it special for all of us to live here.',
    images: ['vetter.jpg', 'vetter-2.jpg', 'vetter-3.jpg'],
    medium: '11ʺ x 17ʺ, silkscreen',
    price: '$40.00',
    title: '“Land of the Free”',
    url: 'http://bradvetterdesign.com',
  },
  gallagher: {
    creator: 'Lauren Gallagher',
    description: 'Love between queens.',
    images: ['gallagher.jpg', 'gallagher-2.jpg', 'gallagher-3.jpg'],
    medium: '11ʺ x 17ʺ, silkscreen',
    price: '$40.00',
    title: '“Queens”',
    url: 'http://lauren-gallagher.com',
  },
  stubenvoll: {
    company: 'Zach Stubenvoll',
    creator: 'Zach Stubenvoll',
    description:
      '“You never truly know someone until you’ve walked a mile in their shoes.” – Unknown',
    images: ['stub.jpg', 'stub-2.jpg', 'stub-3.jpg'],
    medium: '19ʺ x 25ʺ, handcut paper and screenprint',
    price: '$40.00',
    title: '“Home Pride”',
    url: 'http://zachstubenvoll.com',
  },
  marcotte: {
    company: 'Sound & Fury Design Co.',
    creator: 'Matt Marcotte',
    description:
      'I want this piece to help stop discrimination of who our brothers and sisters choose to love. Stand together and love one another.',
    images: ['marcotte.jpg', 'marcotte-2.jpg', 'marcotte-3.jpg'],
    medium: '16ʺ x 20ʺ, rainbow roll',
    price: '$40.00',
    title: '“Sailor Beary”',
    url: 'https://www.facebook.com/SoundAndFuryDesignCo',
  },
  frolichstein: {
    company: 'Frohlichstein, Inc.',
    creator: 'Jason Frolichstein',
    description:
      'We won the fight for gay marriage in Illinois, but 31 other states are still denying citizens equality. Let’s keep fighting the good fight.',
    images: ['frolichstein.jpg', 'frolichstein-2.jpg', 'frolichstein-3.jpg'],
    medium: '19ʺ x 25ʺ, silkscreen',
    price: '$40.00',
    title: '“The Good Fight”',
    url: 'https://dribbble.com/frohlichstein',
  },
};
